import Header from './Header'
import Head from 'next/head'

export default function Home() {
  return (
    <>
    <Head>
      <title>Sample App!!</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    
    <Header/>
    <h1 className="text-3xl font-bold text-black">Hello Next.js</h1>
    <p>
        ここは、かっこよくしていくぜ！
        トップページだからな！
    </p>
    </>
  )
}